# fly.toml app configuration file generated for wahit on 2023-06-19T21:49:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "agpt"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
